name: Discord Notification

on:
  schedule:
    - cron: '0 22 * * *'  # JST 7:00
    - cron: '0 4 * * *'   # JST 13:00
    - cron: '0 14 * * *'  # JST 23:00
  workflow_dispatch:

jobs:
  notify_morning:
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 22 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Send morning message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"【イムセティタスク追加】朝ですよ～起きたら1アド!"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

  notify_midday:
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 4 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Send midday message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"【イムセティ確認】1日も折り返し！イムセティを確認しよう！"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

  notify_night:
    if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 14 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Send night message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"【イムセティタスク整理】おつかれさーん"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

